---
name: cmemc

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  use_cmemc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: install cmemc
        run: |
          pip install -q cmem-cmemc
          cmemc --version
      - name: use cmemc
        run: |
          cmemc graph import graph.ttl $GRAPH
          cmemc graph count $GRAPH
          cmemc graph delete $GRAPH
        env:
          GRAPH: "https://github.com/seebi/cmemc-workflow"
          CMEM_BASE_URI: ${{ secrets.MY_CMEM_BASE_URI }}
          OAUTH_GRANT_TYPE: ${{ secrets.MY_OAUTH_GRANT_TYPE }}
          OAUTH_CLIENT_ID: ${{ secrets.MY_OAUTH_CLIENT_ID }}
          OAUTH_CLIENT_SECRET: ${{ secrets.MY_OAUTH_CLIENT_SECRET }}

