---
name: Test

on:
  push:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Provide Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install cmemc
      run:
        - pip install cmem-cmemc
        - cmemc --version

